### ISSUE TITLE
How can i test your amazing work?

### ISSUE THREAD

**Issue by jiangwqcooler** [lsy17096535/face-landmark#1]
@lsy17096535 hello, i forked your project, but your installing tutorial is too rough， can you tell me the detail of installing face-landmark, thank you very much!

**Comment by lsy17096535** [comment]
@jiangwqcooler You should compile dlib and get dlib.so. Then add this lib to your caffe project. use face_landmark.cpp get 68 points.

**Comment by jiangwqcooler** [comment]
thanks for reply, after compile dlib,  i can't find file dlib.so , i use 
cmake ..  
cmake --build . --config Release

**Comment by lsy17096535** [comment]
@jiangwqcooler 
hi, on my mac os
git clone https://github.com/davisking/dlib.git
cd dlib/examples/
mkdir build
cd build/
cmake -G Xcode ..
cmake --build . --config Release

Then use xcode compile the code.Other platform you should google how to compile your own .so file.

**Comment by jiangwqcooler** [comment]
i cd to python_examples/ and compile dlib and I get dlib.so, is this dlib.so right?

**Comment by lsy17096535** [comment]
@jiangwqcooler sorry, libdlib.a

**Comment by lsy17096535** [comment]
@jiangwqcooler 
I provide cpp example. the lib file name is libdlib.a. If your want to use python to test our model, you have to write your own python test code. I think the dlib.so for python you've got is right.

**Comment by jiangwqcooler** [comment]
@lsy17096535  hi，i still can't run the commond，and my steps is：
1： install dlib and compile
2： download face-landmark
3： download caffe and install in face-landmark dir and compile caffe
4： copy  libdlib.a to caffe/build/lib
5： copy face_landmark.cpp to /caffe/examples/
any steps is wrong? please help ,thanks.

**Comment by jiangwqcooler** [comment]
and i had installed opencv

**Comment by lsy17096535** [comment]
compile face_landmark.cpp like https://github.com/BVLC/caffe/tree/master/examples/cpp_classification
you can get EXE File.
btw, i also got trouble when i first time configure caffe with dlib.

**Comment by jiangwqcooler** [comment]
after set face-landmark.cpp in example dir, i recompile caffe, but i get this error:



.build_release/examples/face_landmark.o: In function `dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&)':
face_landmark.cpp:(.text._ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm[_ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm]+0xe6): undefined reference to `dlib::entropy_decoder_kernel_2::get_target(unsigned int)'
face_landmark.cpp:(.text._ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm[_ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm]+0x18b): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
face_landmark.cpp:(.text._ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm[_ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm]+0x372): undefined reference to `dlib::entropy_decoder_kernel_2::get_target(unsigned int)'
face_landmark.cpp:(.text._ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm[_ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm]+0x390): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
face_landmark.cpp:(.text._ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm[_ZN4dlib30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EE6decodeERm]+0x52b): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
.build_release/examples/face_landmark.o: In function `_GLOBAL__sub_I_face_landmark.cpp':
face_landmark.cpp:(.text.startup+0x81): undefined reference to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'
.build_release/examples/face_landmark.o: In function `dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::istream&, std::ostream&) const':
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x2e): undefined reference to `dlib::entropy_decoder_kernel_2::entropy_decoder_kernel_2()'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x3b): undefined reference to `dlib::entropy_decoder_kernel_2::set_stream(std::istream&)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x143): undefined reference to `dlib::entropy_decoder_kernel_2::get_target(unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x20b): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x40e): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x5f9): undefined reference to `dlib::entropy_decoder_kernel_2::get_target(unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x618): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x678): undefined reference to `dlib::entropy_decoder_kernel_2::get_target(unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x696): undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x791): undefined reference to `dlib::entropy_decoder_kernel_2::~entropy_decoder_kernel_2()'
face_landmark.cpp:(.text._ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo[_ZNK4dlib24compress_stream_kernel_1INS_30entropy_encoder_model_kernel_5ILm257ENS_24entropy_encoder_kernel_2ELm200000ELm4EEENS_30entropy_decoder_model_kernel_5ILm257ENS_24entropy_decoder_kernel_2ELm200000ELm4EEENS_5crc32EE10decompressERSiRSo]+0x7c9): undefined reference to `dlib::entropy_decoder_kernel_2::~entropy_decoder_kernel_2()'
.build_release/examples/face_landmark.o: In function `dlib::get_serialized_frontal_faces()':
face_landmark.cpp:(.text._ZN4dlib28get_serialized_frontal_facesEv[_ZN4dlib28get_serialized_frontal_facesEv]+0x17): undefined reference to `dlib::base64::base64()'
face_landmark.cpp:(.text._ZN4dlib28get_serialized_frontal_facesEv[_ZN4dlib28get_serialized_frontal_facesEv]+0xa44d): undefined reference to `dlib::base64::decode(std::istream&, std::ostream&) const'
face_landmark.cpp:(.text._ZN4dlib28get_serialized_frontal_facesEv[_ZN4dlib28get_serialized_frontal_facesEv]+0xa506): undefined reference to `dlib::base64::~base64()'
face_landmark.cpp:(.text._ZN4dlib28get_serialized_frontal_facesEv[_ZN4dlib28get_serialized_frontal_facesEv]+0xa520): undefined reference to `dlib::base64::~base64()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/face_landmark.bin] Error 1

**Comment by lsy17096535** [comment]
@jiangwqcooler 
根据你的log，感觉程序是可以找到你的头文件，但是找不到你的dlib.a的库。

**Comment by jiangwqcooler** [comment]
我能加你微信请教一下么，有点说不清楚

**Comment by lsy17096535** [comment]
QQ 2634894363

**Comment by jiangwqcooler** [comment]
加不上，需要验证你的邮箱...

**Comment by lsy17096535** [comment]
@jiangwqcooler 把你的QQ给我

**Comment by jiangwqcooler** [comment]
360920474

**Comment by jiangwqcooler** [comment]
can you show me your caffe MakeFile.config？
