### ISSUE TITLE
怎么用dlib才能训练出3M的模型呢？

### ISSUE THREAD

**Issue by jasminezz** [lsy17096535/face-landmark#13]
使用dlib训练了，最小也到了15M，请问是怎么训练出3M模型的呢？

**Comment by lsy17096535** [comment]
@jasminezz 不是用dlib训练，是用dlib作为人脸检测的算法，训练caffe的模型。

**Comment by jasminezz** [comment]
caffe的网络是你自己写的吗？还是基于别的网络重新训练的？

**Comment by jasminezz** [comment]
@lsy17096535 自己写的caffe网络模型进行训练的，是吗？看到Demo.py中有“snap_iter_80000.caffemodel”这个模型，是你训练完后的模型吗？

**Comment by lsy17096535** [comment]
model文件夹下有训练好的模型，直接使用，你先看看caffe的使用，熟悉一下。
