### ISSUE TITLE
你好，能给出模型相关方法的原论文吗？

### ISSUE THREAD

**Issue by kuyun-zhangyang** [lsy17096535/face-landmark#2]
如题

**Comment by lsy17096535** [comment]
@kuyun-zhangyang 
https://github.com/zhzhanp/TCDCN-face-alignment
TCNCN 我们只是做了landmark，其他任务没有做，没有辅助的loss，导致增大模型去拟合。目前在优化模型。

**Comment by kuyun-zhangyang** [comment]
@lsy17096535 ,感谢分享
