### ISSUE TITLE
 'hsi' is not a member of 'dlib::pixel_traits<int>'

### ISSUE THREAD

**Issue by jiangwqcooler** [lsy17096535/face-landmark#3]
@lsy17096535  昨天的问题我解决掉了，今天在caffe里编译face-flandmark.cpp时候又遇到新的问题，尝试多种办法无果，感觉像是dlib的版本问题，我用的是git clone dlid的版本，还请帮忙看一下 

/usr/local/include/dlib/pixel.h:1313:52: error: 'lab' is not a member of 'dlib::pixel_traits<float>'
         typename enable_if_c<pixel_traits<P1>::lab && pixel_traits<P2>::hsi>::type
                                                    ^
/usr/local/include/dlib/pixel.h:1313:52: error: 'hsi' is not a member of 'dlib::pixel_traits<int>'
make: *** [.build_release/examples/face_landmark.o] Error 1

**Comment by DWxqs** [comment]
@lsy17096535，您好，我再编译的时候遇到caffe在Net<float> *net = new Net<float>(network,TEST);这句中断了。layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Input (known types: )网络某层类型没有啊貌似

**Comment by lsy17096535** [comment]
@DWxqs 你用的最新的caffe吗？@jiangwqcooler提供了一个python版的demo，我最会传上来。

**Comment by lsy17096535** [comment]
@jiangwqcooler  Thanks for your python code.

**Comment by DWxqs** [comment]
@lsy17096535 我用的happynear的caffe版本，我先参考链接试试看

**Comment by lsy17096535** [comment]
@DWxqs 你在windows中调用caffe库，需要自己写一个lalyer注册头文件，百度就可以解决。

**Comment by DWxqs** [comment]
@lsy17096535 ，谢谢！确实，写个头文件把layer注册了才行。要么就只能在源caffe.sln里面添加新项目引用libcaffe才行

**Comment by lsy17096535** [comment]
@DWxqs  ok,解决了就好。
