### ISSUE TITLE
five point

### ISSUE THREAD

**Issue by jmu201521121021** [lsy17096535/face-landmark#4]
Hi,how to produce 5 points of face landmark!
thank you!

**Comment by jiangwqcooler** [comment]
i think you can change last layer output number of network，and you should find dataset which only have five points，and modify data process script(change 68 to 5)

**Comment by jmu201521121021** [comment]
ok,thank you!

**Comment by jmu201521121021** [comment]
Hi,you can tell me that   which article is your method based on?
thank you!
@lsy17096535

**Comment by lsy17096535** [comment]
@jmu201521121021  #2
