### ISSUE TITLE
have a question

### ISSUE THREAD

**Issue by kwangrok92** [lsy17096535/face-landmark#41]
Hello, writer.
First of all, I saw your impressive code well.

I'm going to build your code on my computer.
So, I want to know the environment that you have implemented.

For example, Python 3.x, openv-python, numpy, dlib, caffe, etc.

As you know, there are sensitive libraries depending on the version.
I want to know their version.

Thank you !

**Comment by panda-lab** [comment]
You can use python2 ,  opencv 2.4.3  or above version, dlib, caffe. you can also adopt opencv(3.3 or above ) dnn module instead of caffe framework.

**Comment by kwangrok92** [comment]
> You can use python2 , opencv 2.4.3 or above version, dlib, caffe. you can also adopt opencv(3.3 or above ) dnn module instead of caffe framework.

I'll try. 
And then, if i don't know, can i ask you something?

thank you for your answer 👍

**Comment by panda-lab** [comment]
ok
