### ISSUE TITLE
How to train ?

### ISSUE THREAD

**Issue by qqning** [lsy17096535/face-landmark#5]
Hi, @lsy17096535 . Thanks for sharing your code.  Could you provide more infor about your training ?

Where to get the dataset?  
1) In `mainloop.py`,  `trainSetHD5` creates the train data, but the var `CSV_TRAIN` is not set.
2) You mention the original model in #2 . The link also includes two datasets(MTFL and MAFL), but both only provide five facial landmarks.  Do you use their alignment tool to obtains **68** facial landmarks as your offered model outputs **68** landmarks ?

Do you use the same solver prototxt as [VanillaCNN](https://github.com/ishay2b/VanillaCNN/tree/master/ZOO)?

**Comment by lsy17096535** [comment]
@qqning I use 300w, helen, ibug 68points data set. i also reference VanillaCNN.

**Comment by YjDai** [comment]
@qqning  Hi ,Do you know what CSV_TRAIN is ?
