### ISSUE TITLE
训练数据

### ISSUE THREAD

**Issue by boundles** [lsy17096535/face-landmark#6]
麻烦问下训练数据采用的是啥呢？能提供下caffe solver吗

**Comment by lsy17096535** [comment]
@boundles  训练数据用的ibug,300w,helen. solver我找到的话传上来.

**Comment by boundles** [comment]
那你最后的mse是多少呢？我也是把这几个数据合起来训练，但结果有点过拟合，麻烦发我下你的solver哈～
